// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: base_options.command.sql

package sqlc

import (
	"context"
)

const clearMenuBaseOptions = `-- name: ClearMenuBaseOptions :exec
DELETE FROM menu_base_options WHERE menu_id = $1
`

func (q *Queries) ClearMenuBaseOptions(ctx context.Context, menuID int32) error {
	_, err := q.db.Exec(ctx, clearMenuBaseOptions, menuID)
	return err
}

const createMenuBaseOption = `-- name: CreateMenuBaseOption :one
INSERT INTO menu_base_options (menu_id, name, price, sort_order)
VALUES ($1, $2, $3, $4)
RETURNING id, menu_id, name, price, sort_order
`

type CreateMenuBaseOptionParams struct {
	MenuID    int32  `db:"menu_id" json:"menu_id"`
	Name      string `db:"name" json:"name"`
	Price     int64  `db:"price" json:"price"`
	SortOrder int32  `db:"sort_order" json:"sort_order"`
}

func (q *Queries) CreateMenuBaseOption(ctx context.Context, arg CreateMenuBaseOptionParams) (MenuBaseOption, error) {
	row := q.db.QueryRow(ctx, createMenuBaseOption,
		arg.MenuID,
		arg.Name,
		arg.Price,
		arg.SortOrder,
	)
	var i MenuBaseOption
	err := row.Scan(
		&i.ID,
		&i.MenuID,
		&i.Name,
		&i.Price,
		&i.SortOrder,
	)
	return i, err
}
