// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: base_options.query.sql

package sqlc

import (
	"context"
)

const listBaseOptionsByMenuIDs = `-- name: ListBaseOptionsByMenuIDs :many
SELECT id, menu_id, name, price, sort_order
FROM menu_base_options
WHERE menu_id = ANY($1::int[])
ORDER BY menu_id, sort_order, id
`

func (q *Queries) ListBaseOptionsByMenuIDs(ctx context.Context, menuIds []int32) ([]MenuBaseOption, error) {
	rows, err := q.db.Query(ctx, listBaseOptionsByMenuIDs, menuIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MenuBaseOption{}
	for rows.Next() {
		var i MenuBaseOption
		if err := rows.Scan(
			&i.ID,
			&i.MenuID,
			&i.Name,
			&i.Price,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMenuBaseOptions = `-- name: ListMenuBaseOptions :many
SELECT id, menu_id, name, price, sort_order
FROM menu_base_options
WHERE menu_id = $1
ORDER BY sort_order, id
`

func (q *Queries) ListMenuBaseOptions(ctx context.Context, menuID int32) ([]MenuBaseOption, error) {
	rows, err := q.db.Query(ctx, listMenuBaseOptions, menuID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MenuBaseOption{}
	for rows.Next() {
		var i MenuBaseOption
		if err := rows.Scan(
			&i.ID,
			&i.MenuID,
			&i.Name,
			&i.Price,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
