// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cashiers.query.sql

package sqlc

import (
	"context"
)

const getCashier = `-- name: GetCashier :one
SELECT id, login_id, name, pin_hash, active, created_at, updated_at, role
FROM cashiers WHERE id = $1
`

func (q *Queries) GetCashier(ctx context.Context, id int32) (Cashier, error) {
	row := q.db.QueryRow(ctx, getCashier, id)
	var i Cashier
	err := row.Scan(
		&i.ID,
		&i.LoginID,
		&i.Name,
		&i.PinHash,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
	)
	return i, err
}

const getCashierByLoginID = `-- name: GetCashierByLoginID :one
SELECT id, login_id, name, pin_hash, active, created_at, updated_at, role
FROM cashiers WHERE login_id = $1
`

func (q *Queries) GetCashierByLoginID(ctx context.Context, loginID string) (Cashier, error) {
	row := q.db.QueryRow(ctx, getCashierByLoginID, loginID)
	var i Cashier
	err := row.Scan(
		&i.ID,
		&i.LoginID,
		&i.Name,
		&i.PinHash,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
	)
	return i, err
}

const listCashiers = `-- name: ListCashiers :many
SELECT id, login_id, name, pin_hash, active, created_at, updated_at, role
FROM cashiers
ORDER BY login_id
`

func (q *Queries) ListCashiers(ctx context.Context) ([]Cashier, error) {
	rows, err := q.db.Query(ctx, listCashiers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cashier{}
	for rows.Next() {
		var i Cashier
		if err := rows.Scan(
			&i.ID,
			&i.LoginID,
			&i.Name,
			&i.PinHash,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
