// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cash_drawer.command.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendCashDrawerEvent = `-- name: AppendCashDrawerEvent :one
INSERT INTO cash_drawer_audit (event_type, amount, delta, note, actor, terminal)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, event_type, amount, delta, note, actor, terminal, created_at
`

type AppendCashDrawerEventParams struct {
	EventType string      `db:"event_type" json:"event_type"`
	Amount    pgtype.Int8 `db:"amount" json:"amount"`
	Delta     pgtype.Int8 `db:"delta" json:"delta"`
	Note      pgtype.Text `db:"note" json:"note"`
	Actor     pgtype.Text `db:"actor" json:"actor"`
	Terminal  pgtype.Text `db:"terminal" json:"terminal"`
}

func (q *Queries) AppendCashDrawerEvent(ctx context.Context, arg AppendCashDrawerEventParams) (CashDrawerAudit, error) {
	row := q.db.QueryRow(ctx, appendCashDrawerEvent,
		arg.EventType,
		arg.Amount,
		arg.Delta,
		arg.Note,
		arg.Actor,
		arg.Terminal,
	)
	var i CashDrawerAudit
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.Amount,
		&i.Delta,
		&i.Note,
		&i.Actor,
		&i.Terminal,
		&i.CreatedAt,
	)
	return i, err
}
