// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cash_drawer.query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCashDrawerAudit = `-- name: CountCashDrawerAudit :one
SELECT COUNT(*)::bigint FROM cash_drawer_audit
`

func (q *Queries) CountCashDrawerAudit(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCashDrawerAudit)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getCurrentCashDrawerFloat = `-- name: GetCurrentCashDrawerFloat :one
SELECT id, event_type, amount, created_at
FROM cash_drawer_audit
WHERE event_type IN ('set','clear')
ORDER BY created_at DESC, id DESC
LIMIT 1
`

type GetCurrentCashDrawerFloatRow struct {
	ID        int64              `db:"id" json:"id"`
	EventType string             `db:"event_type" json:"event_type"`
	Amount    pgtype.Int8        `db:"amount" json:"amount"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// Returns the most recent absolute float reading (set / clear events carry an
// amount; kicks and open_for_change do not). NULL is acceptable here — it just
// means no float has been recorded yet.
func (q *Queries) GetCurrentCashDrawerFloat(ctx context.Context) (GetCurrentCashDrawerFloatRow, error) {
	row := q.db.QueryRow(ctx, getCurrentCashDrawerFloat)
	var i GetCurrentCashDrawerFloatRow
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const listCashDrawerAudit = `-- name: ListCashDrawerAudit :many
SELECT id, event_type, amount, delta, note, actor, terminal, created_at, denominations
FROM cash_drawer_audit
ORDER BY created_at DESC, id DESC
LIMIT $1 OFFSET $2
`

type ListCashDrawerAuditParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListCashDrawerAudit(ctx context.Context, arg ListCashDrawerAuditParams) ([]CashDrawerAudit, error) {
	rows, err := q.db.Query(ctx, listCashDrawerAudit, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CashDrawerAudit{}
	for rows.Next() {
		var i CashDrawerAudit
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.Amount,
			&i.Delta,
			&i.Note,
			&i.Actor,
			&i.Terminal,
			&i.CreatedAt,
			&i.Denominations,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCashDrawerDenominations = `-- name: ListCashDrawerDenominations :many
SELECT denomination, count, updated_at
FROM cash_drawer_denominations
ORDER BY denomination DESC
`

func (q *Queries) ListCashDrawerDenominations(ctx context.Context) ([]CashDrawerDenomination, error) {
	rows, err := q.db.Query(ctx, listCashDrawerDenominations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CashDrawerDenomination{}
	for rows.Next() {
		var i CashDrawerDenomination
		if err := rows.Scan(&i.Denomination, &i.Count, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
