// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cashiers.command.sql

package sqlc

import (
	"context"
)

const createCashier = `-- name: CreateCashier :one
INSERT INTO cashiers (login_id, name, pin_hash)
VALUES ($1, $2, $3)
RETURNING id, login_id, name, pin_hash, active, created_at, updated_at
`

type CreateCashierParams struct {
	LoginID string `db:"login_id" json:"login_id"`
	Name    string `db:"name" json:"name"`
	PinHash string `db:"pin_hash" json:"pin_hash"`
}

func (q *Queries) CreateCashier(ctx context.Context, arg CreateCashierParams) (Cashier, error) {
	row := q.db.QueryRow(ctx, createCashier, arg.LoginID, arg.Name, arg.PinHash)
	var i Cashier
	err := row.Scan(
		&i.ID,
		&i.LoginID,
		&i.Name,
		&i.PinHash,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCashier = `-- name: DeleteCashier :exec
DELETE FROM cashiers WHERE id = $1
`

func (q *Queries) DeleteCashier(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteCashier, id)
	return err
}

const updateCashier = `-- name: UpdateCashier :one
UPDATE cashiers
SET name       = $2,
    active     = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, login_id, name, pin_hash, active, created_at, updated_at
`

type UpdateCashierParams struct {
	ID     int32  `db:"id" json:"id"`
	Name   string `db:"name" json:"name"`
	Active bool   `db:"active" json:"active"`
}

func (q *Queries) UpdateCashier(ctx context.Context, arg UpdateCashierParams) (Cashier, error) {
	row := q.db.QueryRow(ctx, updateCashier, arg.ID, arg.Name, arg.Active)
	var i Cashier
	err := row.Scan(
		&i.ID,
		&i.LoginID,
		&i.Name,
		&i.PinHash,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCashierPin = `-- name: UpdateCashierPin :one
UPDATE cashiers
SET pin_hash   = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, login_id, name, pin_hash, active, created_at, updated_at
`

type UpdateCashierPinParams struct {
	ID      int32  `db:"id" json:"id"`
	PinHash string `db:"pin_hash" json:"pin_hash"`
}

func (q *Queries) UpdateCashierPin(ctx context.Context, arg UpdateCashierPinParams) (Cashier, error) {
	row := q.db.QueryRow(ctx, updateCashierPin, arg.ID, arg.PinHash)
	var i Cashier
	err := row.Scan(
		&i.ID,
		&i.LoginID,
		&i.Name,
		&i.PinHash,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
