// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: convert.query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listMenuLinksByGroupName = `-- name: ListMenuLinksByGroupName :many
SELECT mog.menu_id        AS menu_id,
       og.id              AS group_id,
       og.owner_menu_id   AS owner_menu_id,
       m.price            AS menu_price
FROM menu_option_groups mog
JOIN option_groups og ON og.id = mog.option_group_id
JOIN menus m          ON m.id  = mog.menu_id
WHERE lower(og.name) = lower($1::text)
ORDER BY mog.menu_id
`

type ListMenuLinksByGroupNameRow struct {
	MenuID      int32       `db:"menu_id" json:"menu_id"`
	GroupID     int32       `db:"group_id" json:"group_id"`
	OwnerMenuID pgtype.Int4 `db:"owner_menu_id" json:"owner_menu_id"`
	MenuPrice   int64       `db:"menu_price" json:"menu_price"`
}

// For the Serve->base-option converter: every (menu, group) link whose group
// name matches case-insensitively, with the menu price + group owner needed
// to convert deltas to absolute prices and decide isolated-clone disposal.
func (q *Queries) ListMenuLinksByGroupName(ctx context.Context, name string) ([]ListMenuLinksByGroupNameRow, error) {
	rows, err := q.db.Query(ctx, listMenuLinksByGroupName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMenuLinksByGroupNameRow{}
	for rows.Next() {
		var i ListMenuLinksByGroupNameRow
		if err := rows.Scan(
			&i.MenuID,
			&i.GroupID,
			&i.OwnerMenuID,
			&i.MenuPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
