// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const topMenusBySales = `-- name: TopMenusBySales :many
SELECT oi.name,
       SUM(oi.qty)::bigint              AS qty_sold,
       SUM(oi.price * oi.qty)::bigint   AS revenue
FROM order_items oi
JOIN orders o ON o.id = oi.order_id
WHERE o.status = 'paid'
  AND o.created_at >= $1::timestamptz
  AND o.created_at < $2::timestamptz
GROUP BY oi.name
ORDER BY qty_sold DESC
LIMIT 10
`

type TopMenusBySalesParams struct {
	Column1 pgtype.Timestamptz `json:"column_1"`
	Column2 pgtype.Timestamptz `json:"column_2"`
}

type TopMenusBySalesRow struct {
	Name    string `json:"name"`
	QtySold int64  `json:"qty_sold"`
	Revenue int64  `json:"revenue"`
}

func (q *Queries) TopMenusBySales(ctx context.Context, arg TopMenusBySalesParams) ([]TopMenusBySalesRow, error) {
	rows, err := q.db.Query(ctx, topMenusBySales, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopMenusBySalesRow{}
	for rows.Next() {
		var i TopMenusBySalesRow
		if err := rows.Scan(&i.Name, &i.QtySold, &i.Revenue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
