// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const periodSummary = `-- name: PeriodSummary :one
SELECT COALESCE(SUM(oi.price * oi.qty), 0)::bigint AS revenue,
       COUNT(DISTINCT o.id)::bigint                AS orders,
       COALESCE(SUM(oi.qty), 0)::bigint            AS items
FROM orders o
LEFT JOIN order_items oi ON oi.order_id = o.id
WHERE o.status = 'paid'
  AND o.created_at >= $1::timestamptz
  AND o.created_at <  $2::timestamptz
`

type PeriodSummaryParams struct {
	FromAt pgtype.Timestamptz `db:"from_at" json:"from_at"`
	ToAt   pgtype.Timestamptz `db:"to_at" json:"to_at"`
}

type PeriodSummaryRow struct {
	Revenue int64 `db:"revenue" json:"revenue"`
	Orders  int64 `db:"orders" json:"orders"`
	Items   int64 `db:"items" json:"items"`
}

func (q *Queries) PeriodSummary(ctx context.Context, arg PeriodSummaryParams) (PeriodSummaryRow, error) {
	row := q.db.QueryRow(ctx, periodSummary, arg.FromAt, arg.ToAt)
	var i PeriodSummaryRow
	err := row.Scan(&i.Revenue, &i.Orders, &i.Items)
	return i, err
}

const salesByDay = `-- name: SalesByDay :many
SELECT date_trunc('day', o.created_at AT TIME ZONE $1::text)::date AS day,
       COALESCE(SUM(oi.price * oi.qty), 0)::bigint AS revenue,
       COUNT(DISTINCT o.id)::bigint                AS orders,
       COALESCE(SUM(oi.qty), 0)::bigint            AS items
FROM orders o
LEFT JOIN order_items oi ON oi.order_id = o.id
WHERE o.status = 'paid'
  AND o.created_at >= $2::timestamptz
  AND o.created_at <  $3::timestamptz
GROUP BY day
ORDER BY day
`

type SalesByDayParams struct {
	Tz     string             `db:"tz" json:"tz"`
	FromAt pgtype.Timestamptz `db:"from_at" json:"from_at"`
	ToAt   pgtype.Timestamptz `db:"to_at" json:"to_at"`
}

type SalesByDayRow struct {
	Day     pgtype.Date `db:"day" json:"day"`
	Revenue int64       `db:"revenue" json:"revenue"`
	Orders  int64       `db:"orders" json:"orders"`
	Items   int64       `db:"items" json:"items"`
}

func (q *Queries) SalesByDay(ctx context.Context, arg SalesByDayParams) ([]SalesByDayRow, error) {
	rows, err := q.db.Query(ctx, salesByDay, arg.Tz, arg.FromAt, arg.ToAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SalesByDayRow{}
	for rows.Next() {
		var i SalesByDayRow
		if err := rows.Scan(
			&i.Day,
			&i.Revenue,
			&i.Orders,
			&i.Items,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const salesByHourDOW = `-- name: SalesByHourDOW :many
SELECT EXTRACT(DOW  FROM o.created_at AT TIME ZONE $1::text)::int AS dow,
       EXTRACT(HOUR FROM o.created_at AT TIME ZONE $1::text)::int AS hour,
       COALESCE(SUM(oi.price * oi.qty), 0)::bigint AS revenue,
       COUNT(DISTINCT o.id)::bigint                AS orders
FROM orders o
LEFT JOIN order_items oi ON oi.order_id = o.id
WHERE o.status = 'paid'
  AND o.created_at >= $2::timestamptz
  AND o.created_at <  $3::timestamptz
GROUP BY dow, hour
ORDER BY dow, hour
`

type SalesByHourDOWParams struct {
	Tz     string             `db:"tz" json:"tz"`
	FromAt pgtype.Timestamptz `db:"from_at" json:"from_at"`
	ToAt   pgtype.Timestamptz `db:"to_at" json:"to_at"`
}

type SalesByHourDOWRow struct {
	Dow     int32 `db:"dow" json:"dow"`
	Hour    int32 `db:"hour" json:"hour"`
	Revenue int64 `db:"revenue" json:"revenue"`
	Orders  int64 `db:"orders" json:"orders"`
}

func (q *Queries) SalesByHourDOW(ctx context.Context, arg SalesByHourDOWParams) ([]SalesByHourDOWRow, error) {
	rows, err := q.db.Query(ctx, salesByHourDOW, arg.Tz, arg.FromAt, arg.ToAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SalesByHourDOWRow{}
	for rows.Next() {
		var i SalesByHourDOWRow
		if err := rows.Scan(
			&i.Dow,
			&i.Hour,
			&i.Revenue,
			&i.Orders,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topMenusBySales = `-- name: TopMenusBySales :many
SELECT oi.name,
       SUM(oi.qty)::bigint              AS qty_sold,
       SUM(oi.price * oi.qty)::bigint   AS revenue
FROM order_items oi
JOIN orders o ON o.id = oi.order_id
WHERE o.status = 'paid'
  AND o.created_at >= $1::timestamptz
  AND o.created_at < $2::timestamptz
GROUP BY oi.name
ORDER BY qty_sold DESC
LIMIT 10
`

type TopMenusBySalesParams struct {
	FromAt pgtype.Timestamptz `db:"from_at" json:"from_at"`
	ToAt   pgtype.Timestamptz `db:"to_at" json:"to_at"`
}

type TopMenusBySalesRow struct {
	Name    string `db:"name" json:"name"`
	QtySold int64  `db:"qty_sold" json:"qty_sold"`
	Revenue int64  `db:"revenue" json:"revenue"`
}

func (q *Queries) TopMenusBySales(ctx context.Context, arg TopMenusBySalesParams) ([]TopMenusBySalesRow, error) {
	rows, err := q.db.Query(ctx, topMenusBySales, arg.FromAt, arg.ToAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopMenusBySalesRow{}
	for rows.Next() {
		var i TopMenusBySalesRow
		if err := rows.Scan(&i.Name, &i.QtySold, &i.Revenue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
