// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: discounts.query.sql

package sqlc

import (
	"context"
)

const getDiscountsByIDs = `-- name: GetDiscountsByIDs :many
SELECT id, name, discount_type, value, active, is_subsidy, created_at
FROM discounts
WHERE id = ANY($1::int[])
ORDER BY id
`

func (q *Queries) GetDiscountsByIDs(ctx context.Context, ids []int32) ([]Discount, error) {
	rows, err := q.db.Query(ctx, getDiscountsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Discount{}
	for rows.Next() {
		var i Discount
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DiscountType,
			&i.Value,
			&i.Active,
			&i.IsSubsidy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveDiscounts = `-- name: ListActiveDiscounts :many
SELECT id, name, discount_type, value, active, is_subsidy, created_at
FROM discounts
WHERE active = true
ORDER BY id
`

func (q *Queries) ListActiveDiscounts(ctx context.Context) ([]Discount, error) {
	rows, err := q.db.Query(ctx, listActiveDiscounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Discount{}
	for rows.Next() {
		var i Discount
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DiscountType,
			&i.Value,
			&i.Active,
			&i.IsSubsidy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiscounts = `-- name: ListDiscounts :many
SELECT id, name, discount_type, value, active, is_subsidy, created_at
FROM discounts
ORDER BY id
`

func (q *Queries) ListDiscounts(ctx context.Context) ([]Discount, error) {
	rows, err := q.db.Query(ctx, listDiscounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Discount{}
	for rows.Next() {
		var i Discount
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DiscountType,
			&i.Value,
			&i.Active,
			&i.IsSubsidy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
