// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: discounts.command.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDiscount = `-- name: CreateDiscount :one
INSERT INTO discounts (name, discount_type, value, active, is_subsidy)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, discount_type, value, active, is_subsidy, created_at
`

type CreateDiscountParams struct {
	Name         string `db:"name" json:"name"`
	DiscountType string `db:"discount_type" json:"discount_type"`
	Value        int64  `db:"value" json:"value"`
	Active       bool   `db:"active" json:"active"`
	IsSubsidy    bool   `db:"is_subsidy" json:"is_subsidy"`
}

func (q *Queries) CreateDiscount(ctx context.Context, arg CreateDiscountParams) (Discount, error) {
	row := q.db.QueryRow(ctx, createDiscount,
		arg.Name,
		arg.DiscountType,
		arg.Value,
		arg.Active,
		arg.IsSubsidy,
	)
	var i Discount
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DiscountType,
		&i.Value,
		&i.Active,
		&i.IsSubsidy,
		&i.CreatedAt,
	)
	return i, err
}

const createOrderDiscount = `-- name: CreateOrderDiscount :exec
INSERT INTO order_discounts (order_id, order_item_id, discount_id, name, discount_type, amount, is_subsidy)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateOrderDiscountParams struct {
	OrderID      int32       `db:"order_id" json:"order_id"`
	OrderItemID  pgtype.Int4 `db:"order_item_id" json:"order_item_id"`
	DiscountID   pgtype.Int4 `db:"discount_id" json:"discount_id"`
	Name         string      `db:"name" json:"name"`
	DiscountType string      `db:"discount_type" json:"discount_type"`
	Amount       int64       `db:"amount" json:"amount"`
	IsSubsidy    bool        `db:"is_subsidy" json:"is_subsidy"`
}

func (q *Queries) CreateOrderDiscount(ctx context.Context, arg CreateOrderDiscountParams) error {
	_, err := q.db.Exec(ctx, createOrderDiscount,
		arg.OrderID,
		arg.OrderItemID,
		arg.DiscountID,
		arg.Name,
		arg.DiscountType,
		arg.Amount,
		arg.IsSubsidy,
	)
	return err
}

const deleteDiscount = `-- name: DeleteDiscount :exec
DELETE FROM discounts WHERE id = $1
`

func (q *Queries) DeleteDiscount(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteDiscount, id)
	return err
}

const updateDiscount = `-- name: UpdateDiscount :one
UPDATE discounts SET name = $2, discount_type = $3, value = $4, active = $5, is_subsidy = $6
WHERE id = $1
RETURNING id, name, discount_type, value, active, is_subsidy, created_at
`

type UpdateDiscountParams struct {
	ID           int32  `db:"id" json:"id"`
	Name         string `db:"name" json:"name"`
	DiscountType string `db:"discount_type" json:"discount_type"`
	Value        int64  `db:"value" json:"value"`
	Active       bool   `db:"active" json:"active"`
	IsSubsidy    bool   `db:"is_subsidy" json:"is_subsidy"`
}

func (q *Queries) UpdateDiscount(ctx context.Context, arg UpdateDiscountParams) (Discount, error) {
	row := q.db.QueryRow(ctx, updateDiscount,
		arg.ID,
		arg.Name,
		arg.DiscountType,
		arg.Value,
		arg.Active,
		arg.IsSubsidy,
	)
	var i Discount
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DiscountType,
		&i.Value,
		&i.Active,
		&i.IsSubsidy,
		&i.CreatedAt,
	)
	return i, err
}
