// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: guest_wifi.command.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateGuestWifiUser = `-- name: ActivateGuestWifiUser :exec
UPDATE guest_wifi_users
SET state = 'active',
    expires_at = now() + interval '2 hours'
WHERE order_id = $1
  AND state = 'assigned'
`

func (q *Queries) ActivateGuestWifiUser(ctx context.Context, orderID pgtype.Int4) error {
	_, err := q.db.Exec(ctx, activateGuestWifiUser, orderID)
	return err
}

const assignGuestWifiUser = `-- name: AssignGuestWifiUser :one
UPDATE guest_wifi_users
SET state = 'assigned',
    order_id = $1,
    assigned_at = now()
WHERE id = $2
RETURNING id, username, state, order_id, assigned_at, expires_at, created_at
`

type AssignGuestWifiUserParams struct {
	OrderID pgtype.Int4 `db:"order_id" json:"order_id"`
	ID      int32       `db:"id" json:"id"`
}

func (q *Queries) AssignGuestWifiUser(ctx context.Context, arg AssignGuestWifiUserParams) (GuestWifiUser, error) {
	row := q.db.QueryRow(ctx, assignGuestWifiUser, arg.OrderID, arg.ID)
	var i GuestWifiUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.State,
		&i.OrderID,
		&i.AssignedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const countPendingGuestWifiUsers = `-- name: CountPendingGuestWifiUsers :one
SELECT count(*) FROM guest_wifi_users WHERE state = 'pending'
`

func (q *Queries) CountPendingGuestWifiUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingGuestWifiUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGuestWifiUser = `-- name: CreateGuestWifiUser :one
INSERT INTO guest_wifi_users (username, state)
VALUES ($1, 'pending')
RETURNING id, username, state, order_id, assigned_at, expires_at, created_at
`

func (q *Queries) CreateGuestWifiUser(ctx context.Context, username string) (GuestWifiUser, error) {
	row := q.db.QueryRow(ctx, createGuestWifiUser, username)
	var i GuestWifiUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.State,
		&i.OrderID,
		&i.AssignedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const expireGuestWifiUsers = `-- name: ExpireGuestWifiUsers :many
UPDATE guest_wifi_users
SET state = 'expired'
WHERE state = 'active'
  AND expires_at < now()
RETURNING id, username, state, order_id, assigned_at, expires_at, created_at
`

func (q *Queries) ExpireGuestWifiUsers(ctx context.Context) ([]GuestWifiUser, error) {
	rows, err := q.db.Query(ctx, expireGuestWifiUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GuestWifiUser{}
	for rows.Next() {
		var i GuestWifiUser
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.State,
			&i.OrderID,
			&i.AssignedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
