// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: guest_wifi.query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAssignedWifiUserByOrder = `-- name: GetAssignedWifiUserByOrder :one
SELECT id, username, state, order_id, assigned_at, expires_at, created_at FROM guest_wifi_users
WHERE order_id = $1
  AND state IN ('assigned', 'active')
LIMIT 1
`

func (q *Queries) GetAssignedWifiUserByOrder(ctx context.Context, orderID pgtype.Int4) (GuestWifiUser, error) {
	row := q.db.QueryRow(ctx, getAssignedWifiUserByOrder, orderID)
	var i GuestWifiUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.State,
		&i.OrderID,
		&i.AssignedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingWifiUser = `-- name: GetPendingWifiUser :one
SELECT id, username, state, order_id, assigned_at, expires_at, created_at FROM guest_wifi_users
WHERE state = 'pending'
ORDER BY id
LIMIT 1
`

func (q *Queries) GetPendingWifiUser(ctx context.Context) (GuestWifiUser, error) {
	row := q.db.QueryRow(ctx, getPendingWifiUser)
	var i GuestWifiUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.State,
		&i.OrderID,
		&i.AssignedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listGuestWifiUsers = `-- name: ListGuestWifiUsers :many
SELECT id, username, state, order_id, assigned_at, expires_at, created_at FROM guest_wifi_users
ORDER BY id
`

func (q *Queries) ListGuestWifiUsers(ctx context.Context) ([]GuestWifiUser, error) {
	rows, err := q.db.Query(ctx, listGuestWifiUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GuestWifiUser{}
	for rows.Next() {
		var i GuestWifiUser
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.State,
			&i.OrderID,
			&i.AssignedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const usernameExists = `-- name: UsernameExists :one
SELECT count(*) FROM guest_wifi_users WHERE username = $1
`

func (q *Queries) UsernameExists(ctx context.Context, username string) (int64, error) {
	row := q.db.QueryRow(ctx, usernameExists, username)
	var count int64
	err := row.Scan(&count)
	return count, err
}
