// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: managerauth.query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getManagerSessionWithUser = `-- name: GetManagerSessionWithUser :one
SELECT s.id            AS session_id,
       s.expires_at    AS expires_at,
       s.revoked_at    AS revoked_at,
       u.id            AS user_id,
       u.username      AS username,
       u.name          AS name,
       u.role          AS role,
       u.active        AS active
FROM manager_sessions s
JOIN manager_users u ON u.id = s.manager_user_id
WHERE s.token_hash = $1
`

type GetManagerSessionWithUserRow struct {
	SessionID int32              `db:"session_id" json:"session_id"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RevokedAt pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	UserID    int32              `db:"user_id" json:"user_id"`
	Username  string             `db:"username" json:"username"`
	Name      string             `db:"name" json:"name"`
	Role      string             `db:"role" json:"role"`
	Active    bool               `db:"active" json:"active"`
}

func (q *Queries) GetManagerSessionWithUser(ctx context.Context, tokenHash string) (GetManagerSessionWithUserRow, error) {
	row := q.db.QueryRow(ctx, getManagerSessionWithUser, tokenHash)
	var i GetManagerSessionWithUserRow
	err := row.Scan(
		&i.SessionID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserID,
		&i.Username,
		&i.Name,
		&i.Role,
		&i.Active,
	)
	return i, err
}

const getManagerUserByUsername = `-- name: GetManagerUserByUsername :one
SELECT id, username, password_hash, name, role, active, created_at, updated_at
FROM manager_users
WHERE username = $1
`

func (q *Queries) GetManagerUserByUsername(ctx context.Context, username string) (ManagerUser, error) {
	row := q.db.QueryRow(ctx, getManagerUserByUsername, username)
	var i ManagerUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
