// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: managerauth.command.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createManagerSession = `-- name: CreateManagerSession :one
INSERT INTO manager_sessions (manager_user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, manager_user_id, token_hash, expires_at, created_at, revoked_at
`

type CreateManagerSessionParams struct {
	ManagerUserID int32              `db:"manager_user_id" json:"manager_user_id"`
	TokenHash     string             `db:"token_hash" json:"token_hash"`
	ExpiresAt     pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateManagerSession(ctx context.Context, arg CreateManagerSessionParams) (ManagerSession, error) {
	row := q.db.QueryRow(ctx, createManagerSession, arg.ManagerUserID, arg.TokenHash, arg.ExpiresAt)
	var i ManagerSession
	err := row.Scan(
		&i.ID,
		&i.ManagerUserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const createManagerUser = `-- name: CreateManagerUser :one
INSERT INTO manager_users (username, password_hash, name, role)
VALUES ($1, $2, $3, $4)
RETURNING id, username, password_hash, name, role, active, created_at, updated_at
`

type CreateManagerUserParams struct {
	Username     string `db:"username" json:"username"`
	PasswordHash string `db:"password_hash" json:"password_hash"`
	Name         string `db:"name" json:"name"`
	Role         string `db:"role" json:"role"`
}

func (q *Queries) CreateManagerUser(ctx context.Context, arg CreateManagerUserParams) (ManagerUser, error) {
	row := q.db.QueryRow(ctx, createManagerUser,
		arg.Username,
		arg.PasswordHash,
		arg.Name,
		arg.Role,
	)
	var i ManagerUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredManagerSessions = `-- name: DeleteExpiredManagerSessions :exec
DELETE FROM manager_sessions
WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredManagerSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredManagerSessions)
	return err
}

const revokeAllManagerSessionsForUser = `-- name: RevokeAllManagerSessionsForUser :exec
UPDATE manager_sessions
SET revoked_at = now()
WHERE manager_user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllManagerSessionsForUser(ctx context.Context, managerUserID int32) error {
	_, err := q.db.Exec(ctx, revokeAllManagerSessionsForUser, managerUserID)
	return err
}

const revokeManagerSession = `-- name: RevokeManagerSession :exec
UPDATE manager_sessions
SET revoked_at = now()
WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeManagerSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeManagerSession, tokenHash)
	return err
}

const updateManagerUserPassword = `-- name: UpdateManagerUserPassword :exec
UPDATE manager_users
SET password_hash = $2,
    updated_at    = now()
WHERE id = $1
`

type UpdateManagerUserPasswordParams struct {
	ID           int32  `db:"id" json:"id"`
	PasswordHash string `db:"password_hash" json:"password_hash"`
}

func (q *Queries) UpdateManagerUserPassword(ctx context.Context, arg UpdateManagerUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateManagerUserPassword, arg.ID, arg.PasswordHash)
	return err
}
