// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: members.query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findMemberByPhone = `-- name: FindMemberByPhone :one
SELECT id, phone, name, points, created_at, updated_at
FROM members
WHERE phone = $1
`

func (q *Queries) FindMemberByPhone(ctx context.Context, phone string) (Member, error) {
	row := q.db.QueryRow(ctx, findMemberByPhone, phone)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Name,
		&i.Points,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMember = `-- name: GetMember :one
SELECT id, phone, name, points, created_at, updated_at
FROM members
WHERE id = $1
`

func (q *Queries) GetMember(ctx context.Context, id int32) (Member, error) {
	row := q.db.QueryRow(ctx, getMember, id)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Name,
		&i.Points,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMembers = `-- name: ListMembers :many
SELECT id, phone, name, points, created_at, updated_at
FROM members
WHERE (
    phone ILIKE '%' || $1 || '%'
    OR name ILIKE '%' || $1 || '%'
    OR $1 IS NULL
)
ORDER BY id
`

func (q *Queries) ListMembers(ctx context.Context, q_ pgtype.Text) ([]Member, error) {
	rows, err := q.db.Query(ctx, listMembers, q_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Member{}
	for rows.Next() {
		var i Member
		if err := rows.Scan(
			&i.ID,
			&i.Phone,
			&i.Name,
			&i.Points,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByMember = `-- name: ListOrdersByMember :many
SELECT o.id, o.code, o.created_at, o.points_earned,
       COALESCE(SUM(oi.price * oi.qty), 0)::bigint AS subtotal
FROM orders o
LEFT JOIN order_items oi ON oi.order_id = o.id
WHERE o.member_id = $1 AND o.status = 'paid'
GROUP BY o.id
ORDER BY o.created_at DESC
`

type ListOrdersByMemberRow struct {
	ID           int32              `db:"id" json:"id"`
	Code         string             `db:"code" json:"code"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	PointsEarned int64              `db:"points_earned" json:"points_earned"`
	Subtotal     int64              `db:"subtotal" json:"subtotal"`
}

func (q *Queries) ListOrdersByMember(ctx context.Context, memberID pgtype.Int4) ([]ListOrdersByMemberRow, error) {
	rows, err := q.db.Query(ctx, listOrdersByMember, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrdersByMemberRow{}
	for rows.Next() {
		var i ListOrdersByMemberRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.CreatedAt,
			&i.PointsEarned,
			&i.Subtotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
