// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: members.command.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMemberPoints = `-- name: AddMemberPoints :one
UPDATE members
SET points = points + $1,
    updated_at = now()
WHERE id = $2
RETURNING id, phone, name, points, created_at, updated_at
`

type AddMemberPointsParams struct {
	Delta int64 `db:"delta" json:"delta"`
	ID    int32 `db:"id" json:"id"`
}

func (q *Queries) AddMemberPoints(ctx context.Context, arg AddMemberPointsParams) (Member, error) {
	row := q.db.QueryRow(ctx, addMemberPoints, arg.Delta, arg.ID)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Name,
		&i.Points,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMember = `-- name: CreateMember :one
INSERT INTO members (phone, name)
VALUES ($1, $2)
RETURNING id, phone, name, points, created_at, updated_at
`

type CreateMemberParams struct {
	Phone string      `db:"phone" json:"phone"`
	Name  pgtype.Text `db:"name" json:"name"`
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, createMember, arg.Phone, arg.Name)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Name,
		&i.Points,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMember = `-- name: DeleteMember :exec
DELETE FROM members WHERE id = $1
`

func (q *Queries) DeleteMember(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteMember, id)
	return err
}

const updateMember = `-- name: UpdateMember :one
UPDATE members
SET phone = $2,
    name = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, phone, name, points, created_at, updated_at
`

type UpdateMemberParams struct {
	ID    int32       `db:"id" json:"id"`
	Phone string      `db:"phone" json:"phone"`
	Name  pgtype.Text `db:"name" json:"name"`
}

func (q *Queries) UpdateMember(ctx context.Context, arg UpdateMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, updateMember, arg.ID, arg.Phone, arg.Name)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Name,
		&i.Points,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
