// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: menu_categories.query.sql

package sqlc

import (
	"context"
)

const getMenuCategory = `-- name: GetMenuCategory :one
SELECT id, name FROM menu_categories WHERE id = $1
`

func (q *Queries) GetMenuCategory(ctx context.Context, id int32) (MenuCategory, error) {
	row := q.db.QueryRow(ctx, getMenuCategory, id)
	var i MenuCategory
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listMenuCategories = `-- name: ListMenuCategories :many
SELECT id, name FROM menu_categories ORDER BY id
`

func (q *Queries) ListMenuCategories(ctx context.Context) ([]MenuCategory, error) {
	rows, err := q.db.Query(ctx, listMenuCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MenuCategory{}
	for rows.Next() {
		var i MenuCategory
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
