// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: menus.command.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMenu = `-- name: CreateMenu :one
INSERT INTO menus (name, price, category_id, vfd_name, favourite)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, price, category_id, vfd_name, active, favourite, sort_order
`

type CreateMenuParams struct {
	Name       string      `db:"name" json:"name"`
	Price      int64       `db:"price" json:"price"`
	CategoryID pgtype.Int4 `db:"category_id" json:"category_id"`
	VfdName    pgtype.Text `db:"vfd_name" json:"vfd_name"`
	Favourite  bool        `db:"favourite" json:"favourite"`
}

func (q *Queries) CreateMenu(ctx context.Context, arg CreateMenuParams) (Menu, error) {
	row := q.db.QueryRow(ctx, createMenu,
		arg.Name,
		arg.Price,
		arg.CategoryID,
		arg.VfdName,
		arg.Favourite,
	)
	var i Menu
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.CategoryID,
		&i.VfdName,
		&i.Active,
		&i.Favourite,
		&i.SortOrder,
	)
	return i, err
}

const deleteMenu = `-- name: DeleteMenu :exec
DELETE FROM menus WHERE id = $1
`

func (q *Queries) DeleteMenu(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteMenu, id)
	return err
}

const setMenuOrder = `-- name: SetMenuOrder :exec
UPDATE menus
SET sort_order = data.ord
FROM (
    SELECT unnest($2::int[]) AS id,
           generate_subscripts($2::int[], 1) AS ord
) AS data
WHERE menus.id = data.id
  AND menus.category_id IS NOT DISTINCT FROM $1
`

type SetMenuOrderParams struct {
	CategoryID pgtype.Int4 `db:"category_id" json:"category_id"`
	Ids        []int32     `db:"ids" json:"ids"`
}

// Assigns sort_order = 1-based position for each id in @ids, but only for menus
// that belong to @category_id (IS NOT DISTINCT FROM handles a NULL category).
// Ids from another category are silently skipped, so a bad request can never
// reorder a different category.
func (q *Queries) SetMenuOrder(ctx context.Context, arg SetMenuOrderParams) error {
	_, err := q.db.Exec(ctx, setMenuOrder, arg.CategoryID, arg.Ids)
	return err
}

const toggleMenu = `-- name: ToggleMenu :one
UPDATE menus SET active = NOT active WHERE id = $1
RETURNING id, name, price, category_id, vfd_name, active, favourite, sort_order
`

func (q *Queries) ToggleMenu(ctx context.Context, id int32) (Menu, error) {
	row := q.db.QueryRow(ctx, toggleMenu, id)
	var i Menu
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.CategoryID,
		&i.VfdName,
		&i.Active,
		&i.Favourite,
		&i.SortOrder,
	)
	return i, err
}

const updateMenu = `-- name: UpdateMenu :one
UPDATE menus SET name = $2, price = $3, category_id = $4, vfd_name = $5, favourite = $6
WHERE id = $1
RETURNING id, name, price, category_id, vfd_name, active, favourite, sort_order
`

type UpdateMenuParams struct {
	ID         int32       `db:"id" json:"id"`
	Name       string      `db:"name" json:"name"`
	Price      int64       `db:"price" json:"price"`
	CategoryID pgtype.Int4 `db:"category_id" json:"category_id"`
	VfdName    pgtype.Text `db:"vfd_name" json:"vfd_name"`
	Favourite  bool        `db:"favourite" json:"favourite"`
}

func (q *Queries) UpdateMenu(ctx context.Context, arg UpdateMenuParams) (Menu, error) {
	row := q.db.QueryRow(ctx, updateMenu,
		arg.ID,
		arg.Name,
		arg.Price,
		arg.CategoryID,
		arg.VfdName,
		arg.Favourite,
	)
	var i Menu
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.CategoryID,
		&i.VfdName,
		&i.Active,
		&i.Favourite,
		&i.SortOrder,
	)
	return i, err
}
