// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: menus.query.sql

package sqlc

import (
	"context"
)

const getMenu = `-- name: GetMenu :one
SELECT id, name, price, category_id, vfd_name FROM menus WHERE id = $1
`

func (q *Queries) GetMenu(ctx context.Context, id int32) (Menu, error) {
	row := q.db.QueryRow(ctx, getMenu, id)
	var i Menu
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.CategoryID,
		&i.VfdName,
	)
	return i, err
}

const listMenus = `-- name: ListMenus :many
SELECT id, name, price, category_id, vfd_name FROM menus ORDER BY id
`

func (q *Queries) ListMenus(ctx context.Context) ([]Menu, error) {
	rows, err := q.db.Query(ctx, listMenus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Menu{}
	for rows.Next() {
		var i Menu
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.CategoryID,
			&i.VfdName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
