// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: menu_categories.command.sql

package sqlc

import (
	"context"
)

const createMenuCategory = `-- name: CreateMenuCategory :one
INSERT INTO menu_categories (name) VALUES ($1)
RETURNING id, name
`

func (q *Queries) CreateMenuCategory(ctx context.Context, name string) (MenuCategory, error) {
	row := q.db.QueryRow(ctx, createMenuCategory, name)
	var i MenuCategory
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const deleteMenuCategory = `-- name: DeleteMenuCategory :exec
DELETE FROM menu_categories WHERE id = $1
`

func (q *Queries) DeleteMenuCategory(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteMenuCategory, id)
	return err
}

const updateMenuCategory = `-- name: UpdateMenuCategory :one
UPDATE menu_categories SET name = $2 WHERE id = $1
RETURNING id, name
`

type UpdateMenuCategoryParams struct {
	ID   int32  `db:"id" json:"id"`
	Name string `db:"name" json:"name"`
}

func (q *Queries) UpdateMenuCategory(ctx context.Context, arg UpdateMenuCategoryParams) (MenuCategory, error) {
	row := q.db.QueryRow(ctx, updateMenuCategory, arg.ID, arg.Name)
	var i MenuCategory
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
