// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CashDrawerAudit struct {
	ID        int64              `db:"id" json:"id"`
	EventType string             `db:"event_type" json:"event_type"`
	Amount    pgtype.Int8        `db:"amount" json:"amount"`
	Delta     pgtype.Int8        `db:"delta" json:"delta"`
	Note      pgtype.Text        `db:"note" json:"note"`
	Actor     pgtype.Text        `db:"actor" json:"actor"`
	Terminal  pgtype.Text        `db:"terminal" json:"terminal"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Menu struct {
	ID         int32       `db:"id" json:"id"`
	Name       string      `db:"name" json:"name"`
	Price      int64       `db:"price" json:"price"`
	CategoryID pgtype.Int4 `db:"category_id" json:"category_id"`
	VfdName    pgtype.Text `db:"vfd_name" json:"vfd_name"`
	Active     bool        `db:"active" json:"active"`
}

type MenuCategory struct {
	ID   int32  `db:"id" json:"id"`
	Name string `db:"name" json:"name"`
}

type MenuOptionGroup struct {
	MenuID        int32 `db:"menu_id" json:"menu_id"`
	OptionGroupID int32 `db:"option_group_id" json:"option_group_id"`
	SortOrder     int32 `db:"sort_order" json:"sort_order"`
}

type Option struct {
	ID            int32  `db:"id" json:"id"`
	OptionGroupID int32  `db:"option_group_id" json:"option_group_id"`
	Name          string `db:"name" json:"name"`
	PriceDelta    int64  `db:"price_delta" json:"price_delta"`
	SortOrder     int32  `db:"sort_order" json:"sort_order"`
}

type OptionGroup struct {
	ID            int32  `db:"id" json:"id"`
	Name          string `db:"name" json:"name"`
	SelectionMode string `db:"selection_mode" json:"selection_mode"`
}

type Order struct {
	ID          int32              `db:"id" json:"id"`
	Code        string             `db:"code" json:"code"`
	Status      string             `db:"status" json:"status"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	HeldAt      pgtype.Timestamptz `db:"held_at" json:"held_at"`
	HeldLabel   pgtype.Text        `db:"held_label" json:"held_label"`
	HeldPayload []byte             `db:"held_payload" json:"held_payload"`
}

type OrderItem struct {
	ID      int32       `db:"id" json:"id"`
	OrderID int32       `db:"order_id" json:"order_id"`
	MenuID  pgtype.Int4 `db:"menu_id" json:"menu_id"`
	Name    string      `db:"name" json:"name"`
	Price   int64       `db:"price" json:"price"`
	Qty     int32       `db:"qty" json:"qty"`
}

type OrderItemOption struct {
	ID          int32       `db:"id" json:"id"`
	OrderItemID int32       `db:"order_item_id" json:"order_item_id"`
	OptionID    pgtype.Int4 `db:"option_id" json:"option_id"`
	Name        string      `db:"name" json:"name"`
	PriceDelta  int64       `db:"price_delta" json:"price_delta"`
}

type Setting struct {
	ID            int32              `db:"id" json:"id"`
	ShopName      string             `db:"shop_name" json:"shop_name"`
	VatPercent    float64            `db:"vat_percent" json:"vat_percent"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Logo          []byte             `db:"logo" json:"logo"`
	LogoMime      pgtype.Text        `db:"logo_mime" json:"logo_mime"`
	ReceiptFooter string             `db:"receipt_footer" json:"receipt_footer"`
}
