// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: options.command.sql

package sqlc

import (
	"context"
)

const attachMenuOptionGroup = `-- name: AttachMenuOptionGroup :exec
INSERT INTO menu_option_groups (menu_id, option_group_id, sort_order)
VALUES ($1, $2, $3)
ON CONFLICT (menu_id, option_group_id) DO UPDATE SET sort_order = EXCLUDED.sort_order
`

type AttachMenuOptionGroupParams struct {
	MenuID        int32 `db:"menu_id" json:"menu_id"`
	OptionGroupID int32 `db:"option_group_id" json:"option_group_id"`
	SortOrder     int32 `db:"sort_order" json:"sort_order"`
}

func (q *Queries) AttachMenuOptionGroup(ctx context.Context, arg AttachMenuOptionGroupParams) error {
	_, err := q.db.Exec(ctx, attachMenuOptionGroup, arg.MenuID, arg.OptionGroupID, arg.SortOrder)
	return err
}

const clearMenuOptionGroups = `-- name: ClearMenuOptionGroups :exec
DELETE FROM menu_option_groups WHERE menu_id = $1
`

func (q *Queries) ClearMenuOptionGroups(ctx context.Context, menuID int32) error {
	_, err := q.db.Exec(ctx, clearMenuOptionGroups, menuID)
	return err
}

const createOption = `-- name: CreateOption :one
INSERT INTO options (option_group_id, name, price_delta, sort_order)
VALUES ($1, $2, $3, $4)
RETURNING id, option_group_id, name, price_delta, sort_order
`

type CreateOptionParams struct {
	OptionGroupID int32  `db:"option_group_id" json:"option_group_id"`
	Name          string `db:"name" json:"name"`
	PriceDelta    int64  `db:"price_delta" json:"price_delta"`
	SortOrder     int32  `db:"sort_order" json:"sort_order"`
}

func (q *Queries) CreateOption(ctx context.Context, arg CreateOptionParams) (Option, error) {
	row := q.db.QueryRow(ctx, createOption,
		arg.OptionGroupID,
		arg.Name,
		arg.PriceDelta,
		arg.SortOrder,
	)
	var i Option
	err := row.Scan(
		&i.ID,
		&i.OptionGroupID,
		&i.Name,
		&i.PriceDelta,
		&i.SortOrder,
	)
	return i, err
}

const deleteOption = `-- name: DeleteOption :exec
DELETE FROM options WHERE id = $1
`

func (q *Queries) DeleteOption(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteOption, id)
	return err
}

const detachMenuOptionGroup = `-- name: DetachMenuOptionGroup :exec
DELETE FROM menu_option_groups WHERE menu_id = $1 AND option_group_id = $2
`

type DetachMenuOptionGroupParams struct {
	MenuID        int32 `db:"menu_id" json:"menu_id"`
	OptionGroupID int32 `db:"option_group_id" json:"option_group_id"`
}

func (q *Queries) DetachMenuOptionGroup(ctx context.Context, arg DetachMenuOptionGroupParams) error {
	_, err := q.db.Exec(ctx, detachMenuOptionGroup, arg.MenuID, arg.OptionGroupID)
	return err
}

const getOptionsByIDs = `-- name: GetOptionsByIDs :many
SELECT id, option_group_id, name, price_delta, sort_order
FROM options
WHERE id = ANY($1::int[])
`

func (q *Queries) GetOptionsByIDs(ctx context.Context, ids []int32) ([]Option, error) {
	rows, err := q.db.Query(ctx, getOptionsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Option{}
	for rows.Next() {
		var i Option
		if err := rows.Scan(
			&i.ID,
			&i.OptionGroupID,
			&i.Name,
			&i.PriceDelta,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOptionsByGroup = `-- name: ListOptionsByGroup :many
SELECT id, option_group_id, name, price_delta, sort_order
FROM options
WHERE option_group_id = $1
ORDER BY sort_order, id
`

func (q *Queries) ListOptionsByGroup(ctx context.Context, optionGroupID int32) ([]Option, error) {
	rows, err := q.db.Query(ctx, listOptionsByGroup, optionGroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Option{}
	for rows.Next() {
		var i Option
		if err := rows.Scan(
			&i.ID,
			&i.OptionGroupID,
			&i.Name,
			&i.PriceDelta,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOption = `-- name: UpdateOption :one
UPDATE options SET name = $2, price_delta = $3, sort_order = $4
WHERE id = $1
RETURNING id, option_group_id, name, price_delta, sort_order
`

type UpdateOptionParams struct {
	ID         int32  `db:"id" json:"id"`
	Name       string `db:"name" json:"name"`
	PriceDelta int64  `db:"price_delta" json:"price_delta"`
	SortOrder  int32  `db:"sort_order" json:"sort_order"`
}

func (q *Queries) UpdateOption(ctx context.Context, arg UpdateOptionParams) (Option, error) {
	row := q.db.QueryRow(ctx, updateOption,
		arg.ID,
		arg.Name,
		arg.PriceDelta,
		arg.SortOrder,
	)
	var i Option
	err := row.Scan(
		&i.ID,
		&i.OptionGroupID,
		&i.Name,
		&i.PriceDelta,
		&i.SortOrder,
	)
	return i, err
}
