// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: option_groups.command.sql

package sqlc

import (
	"context"
)

const createOptionGroup = `-- name: CreateOptionGroup :one
INSERT INTO option_groups (name, selection_mode)
VALUES ($1, $2)
RETURNING id, name, selection_mode
`

type CreateOptionGroupParams struct {
	Name          string `db:"name" json:"name"`
	SelectionMode string `db:"selection_mode" json:"selection_mode"`
}

func (q *Queries) CreateOptionGroup(ctx context.Context, arg CreateOptionGroupParams) (OptionGroup, error) {
	row := q.db.QueryRow(ctx, createOptionGroup, arg.Name, arg.SelectionMode)
	var i OptionGroup
	err := row.Scan(&i.ID, &i.Name, &i.SelectionMode)
	return i, err
}

const deleteOptionGroup = `-- name: DeleteOptionGroup :exec
DELETE FROM option_groups WHERE id = $1
`

func (q *Queries) DeleteOptionGroup(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteOptionGroup, id)
	return err
}

const updateOptionGroup = `-- name: UpdateOptionGroup :one
UPDATE option_groups SET name = $2, selection_mode = $3
WHERE id = $1
RETURNING id, name, selection_mode
`

type UpdateOptionGroupParams struct {
	ID            int32  `db:"id" json:"id"`
	Name          string `db:"name" json:"name"`
	SelectionMode string `db:"selection_mode" json:"selection_mode"`
}

func (q *Queries) UpdateOptionGroup(ctx context.Context, arg UpdateOptionGroupParams) (OptionGroup, error) {
	row := q.db.QueryRow(ctx, updateOptionGroup, arg.ID, arg.Name, arg.SelectionMode)
	var i OptionGroup
	err := row.Scan(&i.ID, &i.Name, &i.SelectionMode)
	return i, err
}
