// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: option_groups.query.sql

package sqlc

import (
	"context"
)

const getOptionGroup = `-- name: GetOptionGroup :one
SELECT id, name, selection_mode FROM option_groups WHERE id = $1
`

func (q *Queries) GetOptionGroup(ctx context.Context, id int32) (OptionGroup, error) {
	row := q.db.QueryRow(ctx, getOptionGroup, id)
	var i OptionGroup
	err := row.Scan(&i.ID, &i.Name, &i.SelectionMode)
	return i, err
}

const getOptionGroupsByIDs = `-- name: GetOptionGroupsByIDs :many
SELECT id, name, selection_mode
FROM option_groups
WHERE id = ANY($1::int[])
ORDER BY id
`

func (q *Queries) GetOptionGroupsByIDs(ctx context.Context, ids []int32) ([]OptionGroup, error) {
	rows, err := q.db.Query(ctx, getOptionGroupsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OptionGroup{}
	for rows.Next() {
		var i OptionGroup
		if err := rows.Scan(&i.ID, &i.Name, &i.SelectionMode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMenuOptionGroupLinks = `-- name: ListMenuOptionGroupLinks :many
SELECT menu_id, option_group_id, sort_order
FROM menu_option_groups
WHERE menu_id = ANY($1::int[])
ORDER BY menu_id, sort_order, option_group_id
`

func (q *Queries) ListMenuOptionGroupLinks(ctx context.Context, menuIds []int32) ([]MenuOptionGroup, error) {
	rows, err := q.db.Query(ctx, listMenuOptionGroupLinks, menuIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MenuOptionGroup{}
	for rows.Next() {
		var i MenuOptionGroup
		if err := rows.Scan(&i.MenuID, &i.OptionGroupID, &i.SortOrder); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOptionGroups = `-- name: ListOptionGroups :many
SELECT id, name, selection_mode FROM option_groups ORDER BY id
`

func (q *Queries) ListOptionGroups(ctx context.Context) ([]OptionGroup, error) {
	rows, err := q.db.Query(ctx, listOptionGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OptionGroup{}
	for rows.Next() {
		var i OptionGroup
		if err := rows.Scan(&i.ID, &i.Name, &i.SelectionMode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOptionsByGroups = `-- name: ListOptionsByGroups :many
SELECT id, option_group_id, name, price_delta, sort_order
FROM options
WHERE option_group_id = ANY($1::int[])
ORDER BY option_group_id, sort_order, id
`

func (q *Queries) ListOptionsByGroups(ctx context.Context, groupIds []int32) ([]Option, error) {
	rows, err := q.db.Query(ctx, listOptionsByGroups, groupIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Option{}
	for rows.Next() {
		var i Option
		if err := rows.Scan(
			&i.ID,
			&i.OptionGroupID,
			&i.Name,
			&i.PriceDelta,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
