// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.command.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (code, status)
VALUES ($1, 'open')
RETURNING id, code, status, created_at
`

func (q *Queries) CreateOrder(ctx context.Context, code string) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder, code)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (order_id, menu_id, name, price, qty)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreateOrderItemParams struct {
	OrderID int32       `db:"order_id" json:"order_id"`
	MenuID  pgtype.Int4 `db:"menu_id" json:"menu_id"`
	Name    string      `db:"name" json:"name"`
	Price   int64       `db:"price" json:"price"`
	Qty     int32       `db:"qty" json:"qty"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (int32, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.MenuID,
		arg.Name,
		arg.Price,
		arg.Qty,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createOrderItemOption = `-- name: CreateOrderItemOption :exec
INSERT INTO order_item_options (order_item_id, option_id, name, price_delta)
VALUES ($1, $2, $3, $4)
`

type CreateOrderItemOptionParams struct {
	OrderItemID int32       `db:"order_item_id" json:"order_item_id"`
	OptionID    pgtype.Int4 `db:"option_id" json:"option_id"`
	Name        string      `db:"name" json:"name"`
	PriceDelta  int64       `db:"price_delta" json:"price_delta"`
}

func (q *Queries) CreateOrderItemOption(ctx context.Context, arg CreateOrderItemOptionParams) error {
	_, err := q.db.Exec(ctx, createOrderItemOption,
		arg.OrderItemID,
		arg.OptionID,
		arg.Name,
		arg.PriceDelta,
	)
	return err
}

const payOrder = `-- name: PayOrder :exec
UPDATE orders SET status = 'paid' WHERE code = $1
`

func (q *Queries) PayOrder(ctx context.Context, code string) error {
	_, err := q.db.Exec(ctx, payOrder, code)
	return err
}
