// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTodayOrders = `-- name: CountTodayOrders :one
SELECT COUNT(*)::bigint AS count
FROM orders
WHERE status = 'paid'
  AND created_at >= CURRENT_DATE
  AND created_at < CURRENT_DATE + INTERVAL '1 day'
`

func (q *Queries) CountTodayOrders(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTodayOrders)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getHeldOrder = `-- name: GetHeldOrder :one
SELECT id, code, status, created_at, held_at, held_label, held_payload
FROM orders
WHERE code = $1 AND status = 'held'
`

type GetHeldOrderRow struct {
	ID          int32              `db:"id" json:"id"`
	Code        string             `db:"code" json:"code"`
	Status      string             `db:"status" json:"status"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	HeldAt      pgtype.Timestamptz `db:"held_at" json:"held_at"`
	HeldLabel   pgtype.Text        `db:"held_label" json:"held_label"`
	HeldPayload []byte             `db:"held_payload" json:"held_payload"`
}

func (q *Queries) GetHeldOrder(ctx context.Context, code string) (GetHeldOrderRow, error) {
	row := q.db.QueryRow(ctx, getHeldOrder, code)
	var i GetHeldOrderRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Status,
		&i.CreatedAt,
		&i.HeldAt,
		&i.HeldLabel,
		&i.HeldPayload,
	)
	return i, err
}

const getOrderByCode = `-- name: GetOrderByCode :one
SELECT id, code, status, created_at FROM orders WHERE code = $1
`

type GetOrderByCodeRow struct {
	ID        int32              `db:"id" json:"id"`
	Code      string             `db:"code" json:"code"`
	Status    string             `db:"status" json:"status"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) GetOrderByCode(ctx context.Context, code string) (GetOrderByCodeRow, error) {
	row := q.db.QueryRow(ctx, getOrderByCode, code)
	var i GetOrderByCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listHeldOrders = `-- name: ListHeldOrders :many
SELECT id, code, status, created_at, held_at, held_label, held_payload
FROM orders
WHERE status = 'held'
ORDER BY held_at DESC NULLS LAST
`

type ListHeldOrdersRow struct {
	ID          int32              `db:"id" json:"id"`
	Code        string             `db:"code" json:"code"`
	Status      string             `db:"status" json:"status"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	HeldAt      pgtype.Timestamptz `db:"held_at" json:"held_at"`
	HeldLabel   pgtype.Text        `db:"held_label" json:"held_label"`
	HeldPayload []byte             `db:"held_payload" json:"held_payload"`
}

func (q *Queries) ListHeldOrders(ctx context.Context) ([]ListHeldOrdersRow, error) {
	rows, err := q.db.Query(ctx, listHeldOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHeldOrdersRow{}
	for rows.Next() {
		var i ListHeldOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Status,
			&i.CreatedAt,
			&i.HeldAt,
			&i.HeldLabel,
			&i.HeldPayload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumOrderItems = `-- name: SumOrderItems :one
SELECT COALESCE(SUM(price * qty), 0)::bigint AS subtotal
FROM order_items
WHERE order_id = $1
`

func (q *Queries) SumOrderItems(ctx context.Context, orderID int32) (int64, error) {
	row := q.db.QueryRow(ctx, sumOrderItems, orderID)
	var subtotal int64
	err := row.Scan(&subtotal)
	return subtotal, err
}

const sumTodaySales = `-- name: SumTodaySales :one
SELECT COALESCE(SUM(oi.price * oi.qty), 0)::bigint AS total
FROM orders o
JOIN order_items oi ON oi.order_id = o.id
WHERE o.status = 'paid'
  AND o.created_at >= CURRENT_DATE
  AND o.created_at < CURRENT_DATE + INTERVAL '1 day'
`

func (q *Queries) SumTodaySales(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, sumTodaySales)
	var total int64
	err := row.Scan(&total)
	return total, err
}
