// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.query.sql

package sqlc

import (
	"context"
)

const countTodayOrders = `-- name: CountTodayOrders :one
SELECT COUNT(*)::bigint AS count
FROM orders
WHERE status = 'paid'
  AND created_at >= CURRENT_DATE
  AND created_at < CURRENT_DATE + INTERVAL '1 day'
`

func (q *Queries) CountTodayOrders(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTodayOrders)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getOrderByCode = `-- name: GetOrderByCode :one
SELECT id, code, status, created_at FROM orders WHERE code = $1
`

func (q *Queries) GetOrderByCode(ctx context.Context, code string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByCode, code)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const sumOrderItems = `-- name: SumOrderItems :one
SELECT COALESCE(SUM(price * qty), 0)::bigint AS subtotal
FROM order_items
WHERE order_id = $1
`

func (q *Queries) SumOrderItems(ctx context.Context, orderID int32) (int64, error) {
	row := q.db.QueryRow(ctx, sumOrderItems, orderID)
	var subtotal int64
	err := row.Scan(&subtotal)
	return subtotal, err
}

const sumTodaySales = `-- name: SumTodaySales :one
SELECT COALESCE(SUM(oi.price * oi.qty), 0)::bigint AS total
FROM orders o
JOIN order_items oi ON oi.order_id = o.id
WHERE o.status = 'paid'
  AND o.created_at >= CURRENT_DATE
  AND o.created_at < CURRENT_DATE + INTERVAL '1 day'
`

func (q *Queries) SumTodaySales(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, sumTodaySales)
	var total int64
	err := row.Scan(&total)
	return total, err
}
