// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.command.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (code, status)
VALUES ($1, 'open')
RETURNING id, code, status, created_at
`

func (q *Queries) CreateOrder(ctx context.Context, code string) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder, code)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :exec
INSERT INTO order_items (order_id, menu_id, name, price, qty)
VALUES ($1, $2, $3, $4, $5)
`

type CreateOrderItemParams struct {
	OrderID int32       `json:"order_id"`
	MenuID  pgtype.Int4 `json:"menu_id"`
	Name    string      `json:"name"`
	Price   int64       `json:"price"`
	Qty     int32       `json:"qty"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) error {
	_, err := q.db.Exec(ctx, createOrderItem,
		arg.OrderID,
		arg.MenuID,
		arg.Name,
		arg.Price,
		arg.Qty,
	)
	return err
}

const payOrder = `-- name: PayOrder :exec
UPDATE orders SET status = 'paid' WHERE code = $1
`

func (q *Queries) PayOrder(ctx context.Context, code string) error {
	_, err := q.db.Exec(ctx, payOrder, code)
	return err
}
