// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOrdersPage = `-- name: CountOrdersPage :one
SELECT COUNT(*)::bigint AS total
FROM orders o
WHERE (o.status = $1 OR $1 = '')
  AND o.created_at >= $2::timestamptz
  AND o.created_at <  $3::timestamptz
`

type CountOrdersPageParams struct {
	Status string             `db:"status" json:"status"`
	FromAt pgtype.Timestamptz `db:"from_at" json:"from_at"`
	ToAt   pgtype.Timestamptz `db:"to_at" json:"to_at"`
}

func (q *Queries) CountOrdersPage(ctx context.Context, arg CountOrdersPageParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOrdersPage, arg.Status, arg.FromAt, arg.ToAt)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const listOrderDiscountsByOrderIDs = `-- name: ListOrderDiscountsByOrderIDs :many
SELECT od.order_id, od.name, od.discount_type, od.amount, od.is_subsidy
FROM order_discounts od
WHERE od.order_id = ANY($1::int[])
ORDER BY od.id
`

type ListOrderDiscountsByOrderIDsRow struct {
	OrderID      int32  `db:"order_id" json:"order_id"`
	Name         string `db:"name" json:"name"`
	DiscountType string `db:"discount_type" json:"discount_type"`
	Amount       int64  `db:"amount" json:"amount"`
	IsSubsidy    bool   `db:"is_subsidy" json:"is_subsidy"`
}

func (q *Queries) ListOrderDiscountsByOrderIDs(ctx context.Context, orderIds []int32) ([]ListOrderDiscountsByOrderIDsRow, error) {
	rows, err := q.db.Query(ctx, listOrderDiscountsByOrderIDs, orderIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrderDiscountsByOrderIDsRow{}
	for rows.Next() {
		var i ListOrderDiscountsByOrderIDsRow
		if err := rows.Scan(
			&i.OrderID,
			&i.Name,
			&i.DiscountType,
			&i.Amount,
			&i.IsSubsidy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderItemOptionsByItemIDs = `-- name: ListOrderItemOptionsByItemIDs :many
SELECT oio.order_item_id, oio.name, oio.price_delta
FROM order_item_options oio
WHERE oio.order_item_id = ANY($1::int[])
ORDER BY oio.id
`

type ListOrderItemOptionsByItemIDsRow struct {
	OrderItemID int32  `db:"order_item_id" json:"order_item_id"`
	Name        string `db:"name" json:"name"`
	PriceDelta  int64  `db:"price_delta" json:"price_delta"`
}

func (q *Queries) ListOrderItemOptionsByItemIDs(ctx context.Context, itemIds []int32) ([]ListOrderItemOptionsByItemIDsRow, error) {
	rows, err := q.db.Query(ctx, listOrderItemOptionsByItemIDs, itemIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrderItemOptionsByItemIDsRow{}
	for rows.Next() {
		var i ListOrderItemOptionsByItemIDsRow
		if err := rows.Scan(&i.OrderItemID, &i.Name, &i.PriceDelta); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderItemsByOrderIDs = `-- name: ListOrderItemsByOrderIDs :many
SELECT oi.id, oi.order_id, oi.name,
       COALESCE(oi.base_option_name, '') AS base_option_name,
       oi.price, oi.qty
FROM order_items oi
WHERE oi.order_id = ANY($1::int[])
ORDER BY oi.id
`

type ListOrderItemsByOrderIDsRow struct {
	ID             int32  `db:"id" json:"id"`
	OrderID        int32  `db:"order_id" json:"order_id"`
	Name           string `db:"name" json:"name"`
	BaseOptionName string `db:"base_option_name" json:"base_option_name"`
	Price          int64  `db:"price" json:"price"`
	Qty            int32  `db:"qty" json:"qty"`
}

func (q *Queries) ListOrderItemsByOrderIDs(ctx context.Context, orderIds []int32) ([]ListOrderItemsByOrderIDsRow, error) {
	rows, err := q.db.Query(ctx, listOrderItemsByOrderIDs, orderIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrderItemsByOrderIDsRow{}
	for rows.Next() {
		var i ListOrderItemsByOrderIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.Name,
			&i.BaseOptionName,
			&i.Price,
			&i.Qty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersPage = `-- name: ListOrdersPage :many
SELECT o.id, o.code, o.status, o.created_at, o.points_earned,
       COALESCE(m.name, '')  AS member_name,
       COALESCE(m.phone, '') AS member_phone
FROM orders o
LEFT JOIN members m ON m.id = o.member_id
WHERE (o.status = $1 OR $1 = '')
  AND o.created_at >= $2::timestamptz
  AND o.created_at <  $3::timestamptz
ORDER BY o.created_at DESC
LIMIT $5 OFFSET $4
`

type ListOrdersPageParams struct {
	Status string             `db:"status" json:"status"`
	FromAt pgtype.Timestamptz `db:"from_at" json:"from_at"`
	ToAt   pgtype.Timestamptz `db:"to_at" json:"to_at"`
	Off    int32              `db:"off" json:"off"`
	Lim    int32              `db:"lim" json:"lim"`
}

type ListOrdersPageRow struct {
	ID           int32              `db:"id" json:"id"`
	Code         string             `db:"code" json:"code"`
	Status       string             `db:"status" json:"status"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	PointsEarned int64              `db:"points_earned" json:"points_earned"`
	MemberName   string             `db:"member_name" json:"member_name"`
	MemberPhone  string             `db:"member_phone" json:"member_phone"`
}

func (q *Queries) ListOrdersPage(ctx context.Context, arg ListOrdersPageParams) ([]ListOrdersPageRow, error) {
	rows, err := q.db.Query(ctx, listOrdersPage,
		arg.Status,
		arg.FromAt,
		arg.ToAt,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrdersPageRow{}
	for rows.Next() {
		var i ListOrdersPageRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Status,
			&i.CreatedAt,
			&i.PointsEarned,
			&i.MemberName,
			&i.MemberPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
