// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.query.sql

package sqlc

import (
	"context"
)

const getSettings = `-- name: GetSettings :one
SELECT id, shop_name, vat_percent, points_per_baht, updated_at FROM settings WHERE id = 1
`

func (q *Queries) GetSettings(ctx context.Context) (Setting, error) {
	row := q.db.QueryRow(ctx, getSettings)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.ShopName,
		&i.VatPercent,
		&i.PointsPerBaht,
		&i.UpdatedAt,
	)
	return i, err
}
