// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.command.sql

package sqlc

import (
	"context"
)

const seedSettings = `-- name: SeedSettings :exec
INSERT INTO settings (id) VALUES (1) ON CONFLICT (id) DO NOTHING
`

func (q *Queries) SeedSettings(ctx context.Context) error {
	_, err := q.db.Exec(ctx, seedSettings)
	return err
}

const updateSettings = `-- name: UpdateSettings :one
UPDATE settings
SET shop_name       = $1,
    vat_percent     = $2,
    points_per_baht = $3,
    updated_at      = now()
WHERE id = 1
RETURNING id, shop_name, vat_percent, points_per_baht, updated_at
`

type UpdateSettingsParams struct {
	ShopName      string  `db:"shop_name" json:"shop_name"`
	VatPercent    float64 `db:"vat_percent" json:"vat_percent"`
	PointsPerBaht float64 `db:"points_per_baht" json:"points_per_baht"`
}

func (q *Queries) UpdateSettings(ctx context.Context, arg UpdateSettingsParams) (Setting, error) {
	row := q.db.QueryRow(ctx, updateSettings, arg.ShopName, arg.VatPercent, arg.PointsPerBaht)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.ShopName,
		&i.VatPercent,
		&i.PointsPerBaht,
		&i.UpdatedAt,
	)
	return i, err
}
