version: '3'

dotenv: [".env"]

tasks:
  migrate-dev:
    cmds:
      - atlas schema apply --url "$PSQL_URL" --to "file://schema.hcl" --dev-url "$PSQL_DEV_URL"

  migrate-prod:
    cmds:
      - atlas schema apply --url "$PSQL_PROD_URL" --to "file://schema.hcl"

  generate-sql-schema:
    cmds:
      - atlas schema inspect -u "$PSQL_URL" --format "{{`{{ sql . }}`}}" > schema.sql

  sqlcgen:
    cmds:
      - sqlc generate
